name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scalaversion: ["2.11.12", "2.12.18", "2.13.11", "3.3.0"]
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v6
      - name: Build
        run: sbt "++${{ matrix.scalaversion }}" publishLocal
      - name: MiMa
        run: sbt "++${{ matrix.scalaversion }}" mimaReportBinaryIssues
      - name: Header check
        run: sbt "++${{ matrix.scalaversion }}" headerCheck
